import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import axios from 'axios';
import Link from 'next/link';

export default function Home() {
  const [data, setData] = useState();

  const apiKey = process.env.NEXT_PUBLIC_apiKey;
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`

  const getTechTransferData = async () => {
    const res = await axios.get(url);
    const info = await res.data;
    console.log(info);
    setData(info);
  }

  useEffect(() => {
    getTechTransferData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainCont}>
        <div className={styles.linkCont}>
          <h1 className={styles.heading}>NASA</h1>
          <Link className={styles.link} href="/polychromatic">Polychromatic</Link>
        </div>
        <main className={styles.main}>
          <div className={styles.grid}>
        {
          data && data.results.map((tech, index) => {
            return (
              <div key={index}>
                {
                  tech && tech.map((t, ind)=>{
                    if (ind === 10) {
                      return (
                        <div key={ind} className={styles.item}>
                          <Image src={t} alt={t} width={200} height={200} />
                        </div>
                      )
                    }
                  })
                }
              </div>
            )
          })
        }
        </div>
        </main>
      </div>
    </>
  )
}
